# Generated by Django 3.2.14 on 2022-09-02 21:06

import cursos.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('icone', models.CharField(choices=[('mobi-mbri-globe-2', 'mobi-mbri-globe-2'), ('mobi-mbri-update', 'mobi-mbri-update'), ('mobi-mbri-user-2', 'mobi-mbri-user-2'), ('mobi-mbri-delivery', 'mobi-mbri-delivery'), ('mobi-mbri-desktop', 'mobi-mbri-desktop'), ('mobi-mbri-features', 'mobi-mbri-features')], default='mobi-mbri-features', max_length=30, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Assunto',
                'verbose_name_plural': 'Assuntos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('desc_geral', models.TextField(verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('globo', 'mobi-mbri-globe-2'), ('update', 'mobi-mbri-update'), ('user', 'mobi-mbri-user-2'), ('delivery', 'mobi-mbri-delivery'), ('desktop', 'mobi-mbri-desktop'), ('features', 'mobi-mbri-features')], default='features', max_length=30, verbose_name='Ícone')),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_assunto', to='cursos.assunto')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-criado'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('caminho', models.URLField()),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_relacionados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField()),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texto_relacionados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', cursos.fields.OrdenaCampos(blank=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_curso', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.FileField(upload_to='imagens')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem_relacionados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('order', cursos.fields.OrdenaCampos(blank=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model_in': ('texto', 'imagem', 'video', 'arquivo')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos_modulo', to='cursos.modulo')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.FileField(upload_to='arquivos')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivo_relacionados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
