# Generated by Django 3.2.14 on 2022-09-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='icone',
            field=models.CharField(choices=[('mobi-mbri-globe-2', 'globo'), ('mobi-mbri-update', 'update'), ('mobi-mbri-user-2', 'user'), ('mobi-mbri-delivery', 'delivery'), ('mobi-mbri-desktop', 'desktop'), ('mobi-mbri-features', 'features')], default='features', max_length=30, verbose_name='Ícone'),
        ),
    ]
